---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: test-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: database
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: rootpass
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        image: mariadb
        ports:
        - containerPort: 3306
          name: mariadb
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        name: mariadb
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mariadb-pv
      volumes:
      - name: mariadb-pv
        persistentVolumeClaim:
          claimName: mariadb-pv
