---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-log-read-exec
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
