---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: populate-database-pod-log-read-exec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-log-read-exec
subjects:
- kind: ServiceAccount
  name: populate-database
