---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: test-migration
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
