apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-migration

resources:
- nginx.yaml
- service.yaml
- route.yaml

configMapGenerator:
- name: nginx-conf
  files:
  - index.html
