apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-migration

resources:
- nginx.yaml
- service.yaml
- route.yaml

configMapGenerator:
- files:
  - index.html
  name: nginx-conf

images:
- digest: sha256:52d41fe3f6b2cdecc1b195b64f74568f21bc1b8976a7ca5bb479013ba98a4beb
  name: nginx
  newName: registry.access.redhat.com/ubi9/nginx-122
