apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: test-migration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        command:
        - nginx
        args:
        - "-g"
        - "daemon off;"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        volumeMounts:
        - name: nginx-conf
          mountPath: /opt/app-root/src/index.html
          subPath: index.html
        resources:
          requests:
            cpu: 100m
            memory: "64Mi"
          limits:
            cpu: 200m
            memory: "256Mi"
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: index.html
            path: index.html
