apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- namespace.yaml
- mariadb.yaml
- pvc.yaml
- service.yaml

secretGenerator:
- name: database-creds
  namespace: test-migration
  literals:
  - username=testuser
  - password=testpass
  - database=testdb
  - rootpass=r00tpw
