---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv
  namespace: test-migration
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
