---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-migration-
  name: openshift-migration
spec:
  targetNamespaces:
  - openshift-migration
  upgradeStrategy: Default
